### PR TITLE
Shifts

### PR DESCRIPTION
**Pull request by rdgifford**
@jonahgeorge
I'm working in the shift model and controller to establish a single shift per night. Right now I've got it so the work_path establishes a new shift every time it's accessed--that's a step in the right direction, but I'd like to be sure a shift is only initiated by the first user of the night. My thinking was from here I would establish validations to ensure a shift could only be created between working hours. Then the shift controllers logic would only create a new shift if a valid shift wasn't already in existence, otherwise a redirect would send the user to the show action for the current shift. What I'm wondering is first off generally--excuse my code exploding everywhere, I've been clumsily tinkering--is this an efficient way to go about setting up shifts? Then second of all, validations on shifts will only effect shifts about to be created, right? I mean, if my database is populated with invalid shifts, the model won't care, right?

### CODE REVIEW

**Comment by rdgifford** [comment]
Alright I did what I could to institute validations on the number of shifts per night. It's not working and I'm not sure why. Hoorah.

**Comment by jonahgeorge** [comment]
Maybe instead of auto-creating a Shift, the first person (or dispatcher) to login for the night just hits a "create shift" button? Less moving parts, same result.

This could be enforced by not allowing rides to be accepted if they come in during a period that doesn't have an associated shift

**Comment by rdgifford** [comment]
Alright, so that plan of attack would require a button_to in place of the link_to on the application view. The validations on the time of shift will still be necessary—shifts shouldn’t be created outside of working hours. Preventing rides from building up without a shift—that’s something I hadn’t even thought about. How about preventing duplicate shifts though, whether a link or a button a validation has to be enforced for that, right? I guess I'm confused. What moving parts does a button shave off? Is using a button not just a reconfiguration of the same parts that a link to the shift_path (with post method) uses?

**Comment by rdgifford** [comment]
Ok. I'm starting to figure out what you meant. Rails won't generate the right URL after it's prevented from creating a new shift, so a new method is going to need to be made for current_shift. I don't know what all that entails but... yeah I'm getting what you mean.

**Comment by jonahgeorge** [comment]
You're moving in the right direction.

Don't get caught up on semantics- a `button_to` or `link_to` doesn't matter, what I meant is that rather than auto-creating it, have a user press (some mechanism) to start that night's shift.

_Other Thoughts:_
- Might be worthwhile to expose a `current_shift` method in your `ApplicationController` that returns the the current shift. Then, in your `RidesController#index` method you can check for the existence of `current_shift`... if it exists, render the table of rides. If it doesn't, hide the table and display a big "Clock In" button. This "Clock In" button would create a Shift record with a `start_date` of `DateTime.now` and a `nil` `end_date`.
- [This line](https://github.com/rdgifford/dds/blob/3f90957206ecfe03305ef4884f82b39ceff3b7ae/config/application.rb#L11) is redundant due to Rail's autoloading and can be removed. If you find that you need it for some reason, there is most likely an error elsewhere.

**Pull request merged**
